### ISSUE TITLE
Lots of errors in RPT and CNTR is not recording

### ISSUE THREAD

**Issue by dixonbegay** [CntoDev/CNTR#5]
**Server OS:** `Windows Server 2012 r2`

**Description:**
Using latest update from master repo and getting lots of errors in rpt file and CNTR is not recording anything.

**Steps to reproduce:**
Run mission with mods listed in RPT log below.

[**RPT File**](https://pastebin.com/TWbkUY1d)

**Comment by lastmikoi** [comment]
This is caused by the current master branch not being *actually* useable as-is: you need to create a `userconfig/cntr/config.hpp` file in your ArmA installation containing the following code (make sure to adapt it depending on your needs): 

```
cntr_captureInterval = 1;
cntr_minPlayerCount = 1;
cntr_endCaptureOnEndMission = true;
cntr_endCaptureOnNoPlayers = true;
cntr_usingAce = false;

cntr_exportPath = "/home/steam/ArmA3/";

cntr_debug = false;
cntr_debugLogEvents = true;
```

We'll make sure to fix this issue in the next release, namely by having this userconfig file completely optional through the use of sane defaults.

**Comment by dixonbegay** [comment]
Ah ok. The only code I had in the `config.hpp` was the `cntr_exporePath` variable set. Thanks for the help.
