### ISSUE TITLE
Feature Request: Better role description

### ISSUE THREAD

**Issue by Gikerl** [CntoDev/CNTR#8]
**Description:**
I would like to see the roles in CNTR be expanded and the current ones renamed if possible. 

Current roles in CNTR are:
- Officer
- Leader
- AR
- AT
- Man
- Sniper

I'd like to see:
- PlatoonLead (prev. Officer)
- SquadLead (prev. Leader)
- Medic (prev. part of Man)
- FireTeamLead (prev. part of Man)
- AR (prev. AR)
- AAR (prev. part of Man)
- AT (prev. AT)
- Sniper (prev. Sniper)
- Pilot (prev. part of Man)
- ArmorCrew (prev. part of Man)

The names are up for debate but i really dislike that the role "man" can be pretty much anything ranging from Medic to Pilot.

**Comment by Abuk007** [comment]
@isakic Is this possible to be implemented?

**Comment by freghar** [comment]
related: https://community.bistudio.com/wiki/roleDescription

**Comment by CptBananaPeel** [comment]
Good suggestion with the role description! 
However (my understanding at least), since we try to make CNTR as broadly accessable to other communities as well, it might not be feasible?

But it is indeed possible to change the names

**Comment by isakic** [comment]
It would be feasible if we made the icons configurable. For example, every community can specify their mappings (roleDescription => icon) in a JSON file that would be loaded when the web player starts. CNTR addon would have to be adapted as well to propagate the information from the mission instead of querying unit loadout as it does now. This would make the icons look different when viewed in our CNTR as opposed to some other community's CNTR. I'll make a draft of the feature once I'm done with my job this month. Any input is welcome.
